### ISSUE TITLE
Add font-awesome in adminhtml

### ISSUE THREAD

**Issue by hieunguyenabcv** [swissup/font-awesome#1]
Hi,

I use your module to use font-awesome's icon in my custom form in Adminhtml of Magento 2.
`<button type="button" class="btn btn-primary btn-lg" id="room_btn" style="width: 100%"
                                    data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Getting room list">
                                Next
                            </button>`
But the icon does not showup. Can you help me to solve this issue?

**Comment by vovayatsyuk** [comment]
Hi,

Latest stable version adds the font to the frontend only.

I've [just commited](https://github.com/swissup/font-awesome/commit/1d75b9e2040777a99acb82e4099a13cefda3ef7b) ability to include font in backend.

You can update module to the latest master branch or apply changes manually:

```bash
cd path/to/font-awesome/module
mv etc/frontend/events.xml etc/events.xml
mv view/frontend view/base

cd path/to/magento/root/folder
php bin/magento setup:static-content:deploy
```

**Comment by hieunguyenabcv** [comment]
Yeah! It worked. Thank you very much. 👍
