### ISSUE TITLE
can update fontawesome to version 5?

### ISSUE THREAD

**Issue by benyang2015** [swissup/font-awesome#3]

**Comment by vovayatsyuk** [comment]
Hi,

There is a [fontawesome5](https://github.com/swissup/font-awesome/tree/fontawesome5) branch available.

We didn't merge it yet into main branch, because some of our products still use an old FontAwesome version.

**Comment by vovayatsyuk** [comment]
I've just created a separate module for version 5: https://github.com/swissup/font-awesome-5.

Will add it to the packagist.org shortly.

**Comment by tigerofasia** [comment]
Awesome thanks @vovayatsyuk !
